"""adds an orbital_period attribute to the Moon class that was created in the previous upgrade.

Revision ID: 12c694a15051
Revises: 37ab7faf1c7d
Create Date: 2025-05-06 18:05:16.338230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c694a15051'
down_revision = '37ab7faf1c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbital_period', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.drop_column('orbital_period')

    # ### end Alembic commands ###
